### PR TITLE
Usernames were made Case insensitive

### PR DESCRIPTION
**Pull request by gabrielci**

### CODE REVIEW

**Comment by rodrigojv** [comment]
@gabrielci el único lugar me parece que es importante hacer la consulta case insenstive es en  `UserDetailsServiceImpl`, siendo que es aquí donde el username viene a partir de lo que ingresa el usuario. En los demás lugares podemos dejar como estaba ya que el username viene de la propia aplicación en esos puntos, es decir, es manejo interno.

**Comment by gabrielci** [comment]
Okay, I will make two Repository methods to obtain the User then, one with Insensitivity and one without, since I refactored the previously existing method I added some extra processing where it isn't necessary, Ill get this fixed as soon as possible

**Comment by gabrielci** [comment]
Done, changes for insensitivity were also left on User creation so it wouldn't let you create "AdMiN" when "Admin" exists.

**Comment by rodrigojv** [comment]
Thank you @gabrielci .

Can you check the Codacy issues?

**Pull request closed without merging**
