### PR TITLE
Add endpoint filter

### PR DESCRIPTION
**Pull request by krconv**
Adds most of the functionality needed to filter snapshots by organization, location, or indicators. A couple of items that still need to be addressed are:
 - Snapshots don't currently have a family ID association, so there isn't a way to get the family information back from these filtered results. My two thoughts are that we can either a) add a family association to snapshots or b) move this filtering functionality over to the families so that they can be filtered, and then there snapshots can be queried for, or c) create a GeographySnapshot DTO which includes information about where the snapshot is located.
 - CSV implementation is hardcoded, which isn't very nice. We could use a CSV library which would allow us to add annotations to the DTOs and then serialize them to CSV, but I don't know what your policy is on using third-party code here.

I'm willing to continue to work on this PR if you'd like me to address these issues. The Snapshot DTO has been hard to work with due to my lack of knowledge of why it was designed, so I would be most comfortable with working with option b of the first issue.

### CODE REVIEW

**Comment by rodrigojv** [comment]
Hi @krconv , thanks for your feedback and contribution.

I'm not sure I understand the first issue you mention. Snapshots and families have a relationship and in the changes for this PR I can see that relationship being used in the `forFamilies` Specification.  Could you please expand on it?

As far as the second issue, we are okay in including any third party library that already solves the problem we're trying to address. So please feel free to do so in this PR.

**Comment by rodrigojv** [comment]
@krconv please take a look to the SnapshotEconomicEntiy#familyUbication field. The idea of that field is to store the location of the family. Perhaps you can use that to solve the first issue.

**Comment by krconv** [comment]
Thank you for your responses! Yes, I'll try to populate the `familyUbication` field with geography information for the family through the entity to DTO mapper for the snapshot.

**Comment by rodrigojv** [comment]
In family ubication we store a string representing the latitude and longitude coordinates of the location.
```
<latitude>,<longitude>
```

For example:
```
-25.2968485,-57.6331085
```

**Comment by rodrigojv** [comment]
You can try to build and run the frontend in your local machine: https://github.com/FundacionParaguaya/fp-psp-frontend

And try to create and fill a new survey using the frontend. In that way you can populate your local database with data and see how the location is stored.

**Comment by krconv** [comment]
Thank you for the pointers! Now I understand why my first question didn't make sense; I didn't realize that the location was already available in the snapshot data. Anyways. I cleaned this up, and was able to get it working on my local environment. Please let me know if there is anything else I can do here!

**Pull request closed without merging**
