### PR TITLE
Changes 'task_tracking' to 'intervention_tracking'

### PR DESCRIPTION
**Pull request by nessv**
A Liquibase script that changes both the name and columns with the
concept 'task_tracking' to 'intervention_tracking'. The table
corresponds to the schema
'survey'.

### CODE REVIEW

**Comment by gzacur** [comment]
@nessv please resolve the conflicts and update the PR 😄

**Comment by nessv** [comment]
Just updated the PR. Please check that everything is ok ;)

**Comment by gzacur** [comment]
@nessv The conflict is not resolved. Are you sure you pushed your changes?

**Comment by nessv** [comment]
@gzacur what about now?🤔

**Pull request closed without merging**
