### PR TITLE
Fixes error in the Activity concept - FPPSP-59 

### PR DESCRIPTION
**Pull request by nessv**

### CODE REVIEW

**Comment by nessv** [comment]
@gzacur I found an error with my original PR. Such error was fixed ;)

**Comment by gzacur** [comment]
@nessv Exists a conflict with file ActivityDTO.java

Please fix the conflict and update the PR.

**Comment by nessv** [comment]
@gzacur I've found an error and updated the PR. The problem should be fixed with the latest commit I did.

**Comment by nessv** [comment]
@gzacur can you check if merging is possible now?

**Pull request merged**
