### PR TITLE
Endpoint to get Terms available Languages

### PR DESCRIPTION
**Pull request by gabrielci**
- Returns a list of TermCondPolDTO where there is a every (Type, Locale) pair must be unique (Type can be "TC" or "PRIV"), this is used to show available languages on the frontend.

### CODE REVIEW

**Comment by rodrigojv** [comment]
Hi @gabrielci , we have some Codacy issues. Could you check them out?

**Comment by gabrielci** [comment]
Will do, it seems its just complaints about spacing, ill have it done in no time

**Comment by rodrigojv** [comment]
@gabrielci the SwaggerConfig has some invalid characters from the merge.

**Comment by gabrielci** [comment]
Fixed

**Comment by rodrigojv** [comment]
I believe the extension should be only `.java`

**Pull request merged**
